name: flutter_braintree
description: Flutter plugin that wraps the native Braintree SDKs. Enables payments with credit cards, PayPal, Google Pay and more.
version: 4.0.0-dev.3
homepage: https://github.com/pikaju/flutter-braintree

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_braintree
        pluginClass: FlutterBraintreePlugin
      ios:
        pluginClass: FlutterBraintreePlugin
